Repository OZ-Coding-School/oz_02_main-005-FE, pull requests merged in 2024-06, with the labels that each got.

#2 docs: 이슈 및 PR 템플릿 작성
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feat.md
  .github/ISSUE_TEMPLATE/refactor.md
  .github/ISSUE_TEMPLATE/style.md
  .github/PULL_REQUEST_TEMPLATE.md
  package-lock.json
  package.json
Labels: docs

#5 docs: 이슈 및 pr 템플릿 작성 수정
  vocca/.github/ISSUE_TEMPLATE/bug.md
  vocca/.github/ISSUE_TEMPLATE/feat.md
  vocca/.github/ISSUE_TEMPLATE/refactor.md
  vocca/.github/ISSUE_TEMPLATE/style.md
  vocca/.github/PULL_REQUEST_TEMPLATE.md
Labels: docs

#8 docs: 이슈 템플릿 수정
  .github/ISSUE_TEMPLATE/style.md
  package-lock.json
  package.json
Labels: docs

#20 16 feat 공용 컴포넌트 레이아웃 구현
  public/icons/SlideButton/active/left.png
  public/icons/SlideButton/active/right.png
  public/icons/SlideButton/index.ts
  public/icons/SlideButton/passive/left.png
  public/icons/SlideButton/passive/right.png
  public/icons/bottomMenuBar/active/comm.png
  public/icons/bottomMenuBar/active/home.png
  public/icons/bottomMenuBar/active/info.png
  public/icons/bottomMenuBar/active/library.png
  public/icons/bottomMenuBar/active/plus.png
  public/icons/bottomMenuBar/index.ts
  public/icons/bottomMenuBar/passive/comm.png
  public/icons/bottomMenuBar/passive/home.png
  public/icons/bottomMenuBar/passive/info.png
  public/icons/bottomMenuBar/passive/library.png
  public/icons/bottomMenuBar/passive/plus.png
  public/next.svg
  public/vercel.svg
  src/app/layout.tsx
  src/app/page.tsx
  src/globals.css
  src/shared/@common/ui/.gitkeep
  src/shared/@common/ui/baseFrame/BaseFrame.tsx
  src/shared/@common/ui/bottomMenu/BottomButton.tsx
  src/shared/@common/ui/bottomMenu/BottomMenuBar.tsx
  src/shared/@common/ui/cardListItem/CardListItem.tsx
  src/shared/@common/ui/input/CommonInput.tsx
  src/shared/@common/ui/slideButton/LeftButton.tsx
  src/shared/@common/ui/slideButton/RightButton.tsx
  src/shared/@common/ui/slideButton/SlideButton.tsx
  tailwind.config.ts
Labels: feature

#18 feat: 공용 컴포넌트 작업
  package-lock.json
  package.json
  public/icons/plus-primary.png
  public/icons/plus.png
  public/icons/private-active.png
  public/icons/private.png
  public/icons/public-active.png
  public/icons/public.png
  public/icons/right-arrow-black.png
  public/icons/right-arrow-gray.png
  public/icons/right-arrow-primary.png
  public/icons/right-arrow-white.png
  public/icons/star-full.svg
  public/icons/star-line.svg
  public/images/logo.png
  src/app/styleguide/page.tsx
  src/shared/@common/ui/Button.tsx
  src/shared/@common/ui/CancelSaveHeader.tsx
  src/shared/@common/ui/Header.tsx
  src/shared/@common/ui/RatingStars.tsx
  src/shared/@common/ui/Tab.tsx
  tailwind.config.ts
Labels: feature

#24 feat: BaseFrame header 적용 및 header, BottomMenuBar 고정, 폴더 이동
  src/app/page.tsx
  src/app/styleguide/page.tsx
  src/shared/@common/ui/Button/Button.tsx
  src/shared/@common/ui/Header/CancelSaveHeader.tsx
  src/shared/@common/ui/Header/Header.tsx
  src/shared/@common/ui/RatingStars/RatingStars.tsx
  src/shared/@common/ui/Tab/Tab.tsx
  src/shared/@common/ui/baseFrame/BaseFrame.tsx
  src/shared/@common/ui/bottomMenu/BottomMenuBar.tsx
  tailwind.config.ts
Labels: feature

#23 21 chore styleguide 폴더 구조 수정 및 css 오류 수정
  src/app/styleguide/hobeom/page.tsx
  src/app/styleguide/hwiyeon/page.tsx
  src/globals.css
  src/shared/@common/ui/slideButton/SlideButton.tsx
Labels: chore, fix

#28 chore: 공용 컴포넌트 수정
  next.config.mjs
  package-lock.json
  package.json
  public/icons/SlideButton/active/left.png
  public/icons/SlideButton/active/right.png
  public/icons/SlideButton/index.ts
  public/icons/SlideButton/left.svg
  public/icons/SlideButton/passive/left.png
  public/icons/SlideButton/passive/right.png
  public/icons/SlideButton/right.svg
  public/icons/bottomMenuBar/active/comm.png
  public/icons/bottomMenuBar/active/home.png
  public/icons/bottomMenuBar/active/info.png
  public/icons/bottomMenuBar/active/library.png
  public/icons/bottomMenuBar/active/plus.png
  public/icons/bottomMenuBar/comm.svg
  public/icons/bottomMenuBar/home.svg
  public/icons/bottomMenuBar/index.ts
  public/icons/bottomMenuBar/info.svg
  public/icons/bottomMenuBar/lib.svg
  public/icons/bottomMenuBar/passive/comm.png
  public/icons/bottomMenuBar/passive/home.png
  public/icons/bottomMenuBar/passive/info.png
  public/icons/bottomMenuBar/passive/library.png
  public/icons/bottomMenuBar/passive/plus.png
  public/icons/bottomMenuBar/plus.svg
  src/app/comm/page.tsx
  src/app/home/page.tsx
  src/app/info/page.tsx
  src/app/lib/page.tsx
  src/app/plus/page.tsx
  src/app/styleguide/hobeom/page.tsx
  src/globals.css
  src/shared/@common/constants/.gitkeep
  src/shared/@common/constants/input.ts
  src/shared/@common/types/.gitkeep
  src/shared/@common/types/input.ts
  src/shared/@common/ui/baseFrame/BaseFrame.tsx
  src/shared/@common/ui/bottomMenu/BottomButton.tsx
  src/shared/@common/ui/bottomMenu/BottomMenuBar.tsx
  src/shared/@common/ui/cardListItem/CardListItem.tsx
  src/shared/@common/ui/input/CommonInput.tsx
  src/shared/@common/ui/input/Input.tsx
  src/shared/@common/ui/slideButton/LeftButton.tsx
  src/shared/@common/ui/slideButton/RightButton.tsx
  src/shared/@common/ui/slideButton/SlideButton.tsx
  src/shared/@common/utils/.gitkeep
  src/shared/@common/utils/validInput.ts
Labels: chore, fix

#27 feat: UI 추가, Button 컴포넌트 수정
  public/icons/back-arrow.png
  public/icons/edit-black.png
  public/icons/edit.png
  public/icons/kakao.svg
  public/images/avatar-select.png
  public/images/avatar.png
  public/images/avatar1.png
  public/images/avatar2.png
  public/images/avatar3.png
  public/images/avatar4.png
  public/images/avatar5.png
  public/images/logo-character.png
  src/app/accountdelete/page.tsx
  src/app/confirmemail/page.tsx
  src/app/landing/page.tsx
  src/app/layout.tsx
  src/app/login/page.tsx
  src/app/mypage/page.tsx
  src/app/page.tsx
  src/app/pointlist/page.tsx
  src/app/privacypolicy/page.tsx
  src/app/profileedit/page.tsx
  src/app/resetpassword/page.tsx
  src/app/settings/page.tsx
  src/app/signup/page.tsx
  src/app/styleguide/hwiyeon/page.tsx
  src/app/verifyemail/page.tsx
  src/globals.css
  src/shared/@common/ui/Button/Button.tsx
  src/shared/@common/ui/Tab/Tab.tsx
  src/shared/@common/ui/baseFrame/BaseFrame.tsx
  src/shared/@common/ui/modal/index.tsx
  src/shared/@common/ui/toggle/Toggle.tsx
  src/views/LandingPage/index.tsx
  src/views/MyPage/AccountDeletePage/index.tsx
  src/views/MyPage/MyPage/index.tsx
  src/views/MyPage/PointListPage/index.tsx
  src/views/MyPage/PrivacyPolicyPage/index.tsx
  src/views/MyPage/ProfileAvatar/index.tsx
  src/views/MyPage/ProfileEditPage/index.tsx
  src/views/MyPage/SettingsPage/index.tsx
  src/views/auth/ComfirmEmailPage/index.tsx
  src/views/auth/LoginPage/.gitkeep
  src/views/auth/LoginPage/index.tsx
  src/views/auth/ResetPasswordPage/index.tsx
  src/views/auth/SignUpPage/.gitkeep
  src/views/auth/SignUpPage/index.tsx
  src/views/auth/VerifyEmailPage/index.tsx
  src/views/landing/.gitkeep
Labels: feature, design

#31 fix: import 수정
  src/app/styleguide/hobeom/page.tsx
  src/shared/@common/ui/modal/index.tsx
  src/views/MyPage/SettingsPage/index.tsx
  src/views/auth/ComfirmEmailPage/index.tsx
Labels: fix

#34 29 feat 보관함 개별 카드뭉치 학습모드 시험모드 페이지 레이아웃 구현
  package-lock.json
  package.json
  public/icons/create/delete.svg
  public/icons/create/excel.svg
  public/icons/create/gpt.svg
  public/icons/create/image.svg
  public/icons/create/index.ts
  public/icons/lib/danger.svg
  public/icons/lib/edit.svg
  public/icons/lib/folder.svg
  public/icons/lib/index.ts
  public/icons/lib/success.svg
  src/app/home/page.tsx
  src/app/lib/cardDecks/[deckName]/page.tsx
  src/app/lib/cardDecks/[deckName]/result/page.tsx
  src/app/lib/cardDecks/[deckName]/study/page.tsx
  src/app/lib/cardDecks/[deckName]/test/page.tsx
  src/app/lib/cardDecks/page.tsx
  src/app/lib/folders/[folderName]/[deckName]/page.tsx
  src/app/lib/folders/[folderName]/page.tsx
  src/app/lib/folders/page.tsx
  src/app/lib/layout.tsx
  src/app/lib/page.tsx
  src/app/plus/cardDeck/excel/page.tsx
  src/app/plus/cardDeck/gpt/page.tsx
  src/app/plus/cardDeck/layout.tsx
  src/app/plus/cardDeck/new/page.tsx
  src/app/plus/folder/page.tsx
  src/app/plus/page.tsx
  src/shared/@common/constants/input.ts
  src/shared/@common/ui/Button/Button.tsx
  src/shared/@common/ui/Header/CancelSaveHeader.tsx
  src/shared/@common/ui/baseFrame/BaseFrame.tsx
  src/shared/@common/ui/bottomMenu/BottomMenuBar.tsx
  src/shared/@common/ui/cardListItem/CardListItem.tsx
  src/shared/@common/ui/input/Input.tsx
  src/shared/@common/ui/modal/index.tsx
  src/shared/@common/utils/validInput.ts
  src/shared/create/CardCreateItem.tsx
  src/shared/library/CardDeckInfo.tsx
  src/shared/library/CardItem.tsx
  src/shared/library/ChoiceItem.tsx
  src/shared/library/DoughnutChart.tsx
  src/shared/library/FolderListItem.tsx
  src/shared/library/ProgressBar.tsx
  src/shared/library/TestCardItem.tsx
  src/shared/library/TestResultItem.tsx
  tailwind.config.ts
Labels: feature, layout

#33 feat: 인풋 적용 및 modal 수정
  src/app/accountdelete/page.tsx
  src/app/confirmemail/page.tsx
  src/app/info/page.tsx
  src/app/landing/page.tsx
  src/app/login/page.tsx
  src/app/mypage/page.tsx
  src/app/pointlist/page.tsx
  src/app/privacypolicy/page.tsx
  src/app/profileedit/page.tsx
  src/app/resetpassword/page.tsx
  src/app/settings/page.tsx
  src/app/signup/page.tsx
  src/app/verifyemail/page.tsx
  src/shared/@common/ui/Button/Button.tsx
  src/shared/@common/ui/RatingStars/RatingStars.tsx
  src/shared/@common/ui/Tab/Tab.tsx
  src/shared/@common/ui/input/Input.tsx
  src/shared/@common/ui/modal/index.tsx
  src/views/MyPage/MyPage/index.tsx
  src/views/MyPage/ProfileAvatar/index.tsx
  src/views/auth/EmailTemplate/index.tsx
  src/views/auth/LoginPage/index.tsx
  src/views/auth/SignUpPage/index.tsx
  src/views/auth/VerifyEmailPage/index.tsx
Labels: feature

#38 feat: modal 컴포넌트 수정
  .github/ISSUE_TEMPLATE/design.md
  .github/ISSUE_TEMPLATE/feat.md
  .github/ISSUE_TEMPLATE/refactor.md
  src/app/lib/folders/page.tsx
  src/app/plus/cardDeck/gpt/page.tsx
  src/app/plus/cardDeck/new/page.tsx
  src/shared/@common/ui/modal/index.tsx
  src/shared/library/CardDeckInfo.tsx
Labels: feature

#42 40 feat 커뮤니티 페이지 레이아웃 구현
  public/icons/comm/dropdown.svg
  public/icons/comm/index.ts
  public/images/index.ts
  public/images/search.png
  src/app/comm/[decks]/[deck]/page.tsx
  src/app/comm/[decks]/page.tsx
  src/app/comm/layout.tsx
  src/app/comm/page.tsx
  src/app/lib/cardDecks/page.tsx
  src/app/plus/cardDeck/gpt/page.tsx
  src/app/plus/cardDeck/layout.tsx
  src/app/plus/folder/page.tsx
  src/app/plus/page.tsx
  src/app/styleguide/hobeom/page.tsx
  src/shared/@common/ui/Button/Button.tsx
  src/shared/@common/ui/Header/Header.tsx
  src/shared/@common/ui/RatingStars/RatingStars.tsx
  src/shared/@common/ui/baseFrame/BaseFrame.tsx
  src/shared/@common/ui/bottomMenu/BottomMenuBar.tsx
  src/shared/@common/ui/cardListItem/CardListItem.tsx
  src/shared/comm/Banner.tsx
  src/shared/comm/CardDeckItem.tsx
  src/shared/comm/CardDeckList.tsx
  src/shared/comm/CommentArea.tsx
  src/shared/comm/CommentItem.tsx
  src/shared/comm/ReplyItem.tsx
  src/shared/comm/SearchInput.tsx
  src/shared/comm/SelectListButton.tsx
  src/shared/comm/SelectModal.tsx
  src/shared/comm/WriteArea.tsx
  src/shared/library/DoughnutChart.tsx
  src/views/community/CardDeckItemPage.tsx
  src/views/community/CardDeckListPage.tsx
  src/views/community/constants/index.ts
  src/views/plus/FolderCreationPage.tsx
  src/views/plus/PlusPage.tsx
Labels: feature, layout

#45 feat: 이메일 템플릿 수정
  src/app/emailtemplate/page.tsx
  src/views/auth/EmailTemplate/EmailUpdateTemplatePage.tsx
  src/views/auth/EmailTemplate/IdFindTemplatePage.tsx
  src/views/auth/EmailTemplate/PwFindTemplatePage.tsx
  src/views/auth/EmailTemplate/index.tsx
Labels: feature
